- name: install glusterfs client
  apt:
    name: glusterfs-client
    state: present
    update_cache: yes
  tags: node,glusterfs-client

- name: Check if join is already done
  stat:
    path: "/etc/kubernetes/kubelet.conf"
  register: kubelet_conf
  tags: node,join

- name: Join node to master
  shell: "{{ hostvars[groups['master'][0]]['join_command']['stdout'] }}"
  when: not kubelet_conf.stat.exists
  tags: node,join
