- name: add kubernetes repo key
  apt_key: 
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
  tags: common,repo-kubernetes

- name: add kubernetes repo
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    state: present
  tags: common,repo-kubernetes
